{% set org = "tdegeus" %}
{% set name = "GMatTensor" %}
{% set version = "0.7.2" %}

package:
  name: {{ name|lower }}-split
  version: {{ version }}

source:
  url: https://github.com/{{ org }}/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 05e4269028f09ca96059357882bced7ae06afb3d58569f4dfcac4b6d60d31f3c

build:
  number: 0
  script_env: SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}
  requirements:
    - {{ compiler('cxx') }}

outputs:

  - name: {{ name|lower }}

    script: install.sh  # [unix]
    script: install.bat  # [win]

    requirements:
      build:
        - {{ compiler('cxx') }}
        - cmake
        - make  # [unix]
        - python  # [build_platform != target_platform]
        - cross-python_{{ target_platform }}  # [build_platform != target_platform]
        - setuptools_scm  # [build_platform != target_platform]
      host:
        - setuptools_scm
        - xtensor
      run:
        - xtensor

    test:
      commands:
        - test -d ${PREFIX}/include/{{ name }}  # [unix]
        - test -f ${PREFIX}/include/{{ name }}/Cartesian2d.h  # [unix]
        - test -f ${PREFIX}/include/{{ name }}/Cartesian3d.h  # [unix]
        - test -f ${PREFIX}/lib/cmake/{{ name }}/{{ name }}Config.cmake  # [unix]
        - if exist %LIBRARY_PREFIX%\include\{{ name }}\Cartesian2d.h (exit 0) else (exit 1)  # [win]
        - if exist %LIBRARY_PREFIX%\include\{{ name }}\Cartesian3d.h (exit 0) else (exit 1)  # [win]
        - if exist %LIBRARY_PREFIX%\lib\cmake\{{ name }}Config.cmake (exit 0) else (exit 1)  # [win]

  - name: python-{{ name|lower }}

    script: install_python.sh  # [unix]
    script: install_python.bat  # [win]

    requirements:
      build:
        - {{ compiler('cxx') }}
        - cmake
        - ninja
        - python  # [build_platform != target_platform]
        - cross-python_{{ target_platform }}  # [build_platform != target_platform]
        - numpy  # [build_platform != target_platform]
        - setuptools_scm  # [build_platform != target_platform]
      host:
        - python
        - pip
        - setuptools_scm
        - numpy
        - xtensor
        - xtensor-python
        - pyxtensor  # [win]
      run:
        - python

    test:
      imports:
        - {{ name }}
      commands:
        - pip check
      requires:
        - pip

about:
  home: https://github.com/{{ org }}/{{ name }}
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Tensor definitions supporting several GMat models.
  description: Tensor definitions supporting several GMat models.
  doc_url: https://{{ org }}.github.io/{{ name }}
  dev_url: https://github.com/{{ org }}/{{ name }}

extra:
  recipe-maintainers:
    - tdegeus
