{% set name = "gmattensor" %}
{% set version = "0.6.0" %}
{% set sha256 = "417bd7af1bb334db418e3712d53e4ea7f042a083ded3ca34c45ca440886efffd" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/tdegeus/GMatTensor/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - make  # [unix]
    - xtensor
  run:
    - xtensor

test:
  commands:
    - test -d ${PREFIX}/include/GMatTensor  # [unix]
    - test -f ${PREFIX}/include/GMatTensor/Cartesian2d.h  # [unix]
    - test -f ${PREFIX}/include/GMatTensor/Cartesian3d.h  # [unix]
    - test -f ${PREFIX}/lib/cmake/GMatTensor/GMatTensorConfig.cmake  # [unix]
    - if exist %LIBRARY_PREFIX%\include\GMatTensor\Cartesian2d.h (exit 0) else (exit 1)  # [win]
    - if exist %LIBRARY_PREFIX%\include\GMatTensor\Cartesian3d.h (exit 0) else (exit 1)  # [win]
    - if exist %LIBRARY_PREFIX%\lib\cmake\GMatTensorConfig.cmake (exit 0) else (exit 1)  # [win]

about:
  home: https://github.com/tdegeus/GMatTensor
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Tensor definitions supporting several GMat models.
  description: Tensor definitions supporting several GMat models.
  doc_url: https://github.com/tdegeus/GMatTensor
  dev_url: https://github.com/tdegeus/GMatTensor

extra:
  recipe-maintainers:
    - tdegeus
