{% set org = "tdegeus" %}
{% set name = "GMatTensor" %}
{% set version = "0.10.6" %}

package:
  name: {{ name|lower }}-split
  version: {{ version }}

source:
  url: https://github.com/{{ org }}/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: bbbd486f44cba693a77d216709631c2c3139b1e7e523ff1fcced2100c4a19e59

build:
  number: 3

outputs:

  - name: {{ name|lower }}

    script: install.sh  # [unix]
    script: install.bat  # [win]

    build:
      script_env: SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}

    requirements:
      build:
        - {{ compiler('cxx') }}
        - {{ stdlib("c") }}
        - {{ stdlib("c") }}
        - cmake
        - make  # [unix]
      host:
        - xtensor
      run:
        - xtensor

    test:
      commands:
        - test -d ${PREFIX}/include/{{ name }}  # [unix]
        - test -f ${PREFIX}/include/{{ name }}/Cartesian2d.h  # [unix]
        - test -f ${PREFIX}/include/{{ name }}/Cartesian3d.h  # [unix]
        - test -f ${PREFIX}/lib/cmake/{{ name }}/{{ name }}Config.cmake  # [unix]
        - if exist %LIBRARY_PREFIX%\include\{{ name }}\Cartesian2d.h (exit 0) else (exit 1)  # [win]
        - if exist %LIBRARY_PREFIX%\include\{{ name }}\Cartesian3d.h (exit 0) else (exit 1)  # [win]
        - if exist %LIBRARY_PREFIX%\lib\cmake\{{ name }}Config.cmake (exit 0) else (exit 1)  # [win]

  - name: python-{{ name|lower }}

    script: install_python.sh  # [unix]
    script: install_python.bat  # [win]

    build:
      script_env: SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}
      skip: true  # [python_impl == 'pypy']

    requirements:
      build:
        - python                              # [build_platform != target_platform]
        - cross-python_{{ target_platform }}  # [build_platform != target_platform]
        - numpy *                             # [build_platform != target_platform]
        - setuptools_scm                      # [build_platform != target_platform]
        - {{ compiler('cxx') }}
        - {{ stdlib("c") }}
        - {{ stdlib("c") }}
        - cmake
        - make  # [unix]
        - ninja
      host:
        - numpy *
        - pip
        - pybind11
        - pybind11-abi
        - python
        - scikit-build
        - setuptools_scm
        - xtensor
        - xtensor-python
      run:
        - numpy *
        - python

    test:
      imports:
        - {{ name }}
      commands:
        - pip check
        - python -c "import {{ name }}; assert {{ name }}.version() == '{{ version }}'"
      requires:
        - pip

about:
  home: https://github.com/{{ org }}/{{ name }}
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Tensor definitions supporting several GMat models.
  description: Tensor definitions supporting several GMat models.
  doc_url: https://{{ org }}.github.io/{{ name }}
  dev_url: https://github.com/{{ org }}/{{ name }}

extra:
  recipe-maintainers:
    - tdegeus
